INSERT INTO TB_EQUIPE_MANUTENCAO (NOME, QUANTIDADE_INTEGRANTES, ESPECIALIDADE)
VALUES ('Equipe Alfa', 6, 'Rocada manual');

INSERT INTO TB_EQUIPE_MANUTENCAO (NOME, QUANTIDADE_INTEGRANTES, ESPECIALIDADE)
VALUES ('Equipe Beta', 8, 'Rocada mecanizada e pulverizacao');

INSERT INTO TB_TRECHO_RODOVIA
    (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO_CM, TIPO_AMBIENTE, RISCO_OPERACIONAL, ID_EQUIPE)
SELECT 10.0, 11.0, 92.0, 'umido', 'alto', ID_EQUIPE
FROM TB_EQUIPE_MANUTENCAO
WHERE NOME = 'Equipe Alfa';

INSERT INTO TB_TRECHO_RODOVIA
    (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO_CM, TIPO_AMBIENTE, RISCO_OPERACIONAL, ID_EQUIPE)
SELECT 20.0, 21.0, 85.0, 'seco', 'baixo', ID_EQUIPE
FROM TB_EQUIPE_MANUTENCAO
WHERE NOME = 'Equipe Beta';

INSERT INTO TB_TRECHO_RODOVIA
    (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO_CM, TIPO_AMBIENTE, RISCO_OPERACIONAL, ID_EQUIPE)
SELECT 30.0, 31.0, 55.0, 'umido', 'baixo', ID_EQUIPE
FROM TB_EQUIPE_MANUTENCAO
WHERE NOME = 'Equipe Beta';

INSERT INTO TB_TRECHO_RODOVIA
    (KM_INICIAL, KM_FINAL, ALTURA_VEGETACAO_CM, TIPO_AMBIENTE, RISCO_OPERACIONAL, ID_EQUIPE)
SELECT 40.0, 41.0, 25.0, 'seco', 'baixo', ID_EQUIPE
FROM TB_EQUIPE_MANUTENCAO
WHERE NOME = 'Equipe Alfa';

INSERT INTO TB_INTERVENCAO_OPERACIONAL (TIPO, ID_TRECHO, ID_EQUIPE)
SELECT 'ROCADA_MANUAL', T.ID_TRECHO, E.ID_EQUIPE
FROM TB_TRECHO_RODOVIA T
JOIN TB_EQUIPE_MANUTENCAO E ON E.NOME = 'Equipe Alfa'
WHERE T.KM_INICIAL = 10.0 AND T.KM_FINAL = 11.0;

INSERT INTO TB_INTERVENCAO_OPERACIONAL (TIPO, ID_TRECHO, ID_EQUIPE)
SELECT 'ROCADA_MECANIZADA', T.ID_TRECHO, E.ID_EQUIPE
FROM TB_TRECHO_RODOVIA T
JOIN TB_EQUIPE_MANUTENCAO E ON E.NOME = 'Equipe Beta'
WHERE T.KM_INICIAL = 20.0 AND T.KM_FINAL = 21.0;

INSERT INTO TB_INTERVENCAO_OPERACIONAL (TIPO, ID_TRECHO, ID_EQUIPE)
SELECT 'PULVERIZACAO', T.ID_TRECHO, E.ID_EQUIPE
FROM TB_TRECHO_RODOVIA T
JOIN TB_EQUIPE_MANUTENCAO E ON E.NOME = 'Equipe Beta'
WHERE T.KM_INICIAL = 30.0 AND T.KM_FINAL = 31.0;

INSERT INTO TB_RELATORIO_PRIORIDADE
    (QUANTIDADE_URGENTE, QUANTIDADE_CRITICO, QUANTIDADE_ATENCAO, QUANTIDADE_NORMAL, RESUMO)
VALUES (1, 1, 1, 1, 'Dados iniciais: uma ocorrencia de cada prioridade');

COMMIT;
